### ISSUE TITLE
SDK functions not routed to the same PrivX node

### ISSUE THREAD

**Issue by vfosterm-ssh** [SSHcom/privx-sdk-for-python#98]
Some SDK functions require requests to be routed to the same node. 
All API calls that require a session_id require the session ID to be established on the same node that the API call is routed to.
Currently the SDK doesn't support sticky session cookies so the only option is to bypass the loadbalancer, which is not always possible.

**Comment by RomanSemkin** [comment]
check this PR https://github.com/SSHcom/privx-sdk-for-python/pull/101, please
